### ISSUE TITLE
Character registration results in wrong character.

### ISSUE THREAD

**Issue by rsfiye** [Dusk-Argentum/Mudbot#1]
Hey Dusk. We has an issue where a character by the name of 'Ana Whit' from Jenova linked and it pulled up a different character by the name of 'Aiyana White' on the same server.

Here's a screenshot of it happening on discord. Its easily reproduced.

![image](https://user-images.githubusercontent.com/30898632/91097596-9c60f600-e625-11ea-9eb0-2536e3c5a2e8.png)

A link to Ana Whit's lodestone profile: https://na.finalfantasyxiv.com/lodestone/character/28001686/

**Comment by Dusk-Argentum** [comment]
Thanks for your report!

Cause: Seems to be that "Aiyana White"'s name contains the name "Ana Whit", when the difference between upper and lower case is ignored. This is likely due to the `re.IGNORECASE` flag applied to the Regex search on line 685.

Solution: The Regex needs to be adjusted so that the case of the first letter of the first name and the first letter of the last name are both upper case, so that names within name (such as in this issue) do not cause a false positive.

ETA: Soon-ish? The beginning of this week is hectic for me; but it should be done by evening on Wednesday (EST) at the latest.

Priority: Low. This issue is easily manually bypassed and does not result in a function error.

**Comment by Dusk-Argentum** [comment]
Effectively patched via v1.0.5.
